# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
defaults:
  -
  scope:
  path: ""
  type: "posts"
  values:
  is_post: true
  thumbnail: https://user-images.githubusercontent.com/35059428/64468325-069f3300-d156-11e9-80ec-45e98bd19703.jpg

# Site settings
title: SJ log
description: Pursuing Wholesome Nomad life journey # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
email: sjisyours@gmail.com
url: "https://wholesome-sj.github.io" # the base hostname & protocol for your site
twitter_username: sjisyours 
github_username:  wholesome-sj
blog_owner_pic : https://user-images.githubusercontent.com/35059428/57188024-86a85880-6f2a-11e9-8c25-2a0ef0cce90f.png
# Social Account
instagram_url : https://instagram.com/wholesome.nomad.sj
youtube_url : https://www.youtube.com/channel/UC4kb6gxOTKVBIKcFfZPiwoQ/
permalink: /:path

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
google_analytics: UA-116676814-1
disqus_shortname: Ollagada

# used this for post_excerpt at index_page
excerpt_separator: <-!->

# plugins
plugins:
    - jekyll-sitemap
    - jekyll-mermaid

permalink: /:path