# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SJ
description: Wholesome Nomad Life # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
email: sjisyours@gmail.com
url: "https://wholesome-sj.github.io" # the base hostname & protocol for your site
twitter_username: sjisyours 
github_username:  wholesome-sj
blog_owner_pic : https://user-images.githubusercontent.com/35059428/57188024-86a85880-6f2a-11e9-8c25-2a0ef0cce90f.png
# Social Account
instagram_username : wholesome.sj
youtube_channel : UCYGePlIyuiL4n2aSJbf327g
permalink: /:path

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
google_analytics: UA-116676814-1
disqus_shortname: Ollagada

# used this for post_excerpt at index_page
excerpt_separator: <-!->

# plugins
plugins:
    - jekyll-sitemap

permalink: /:path