# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sj
email: sjisyours@gmail.com
description: Wholesome life # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ollagada.github.io" # the base hostname & protocol for your site
twitter_username: sjisyours 
github_username:  Ollagada

# instagram
instagram_username : wholsome.sj

# instafeed.js
instafeed_ellie_user_id : 10439974221
instafeed_client_id : ca060da1e05e474788d194eb407b5c12
instafeed_accessToken : 10439974221.ca060da.7ca2ca8aec504583a396f67cbc1b82f9
ellie_instagram_username : fullyraw.jennie_md

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
google_analytics: UA-116676814-1
disqus_shortname: Ollagada

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->

# plugins
plugins:
    - jekyll-sitemap
